// AXI_DMA.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module AXI_DMA (
		input  wire  clk_clk,              //              clk.clk
		output wire  msgdma_0_csr_irq_irq, // msgdma_0_csr_irq.irq
		input  wire  reset_reset_n         //            reset.reset_n
	);

	wire   [31:0] mm_master_bfm_0_m0_readdata;                             // mm_interconnect_0:mm_master_bfm_0_m0_readdata -> mm_master_bfm_0:avm_readdata
	wire          mm_master_bfm_0_m0_waitrequest;                          // mm_interconnect_0:mm_master_bfm_0_m0_waitrequest -> mm_master_bfm_0:avm_waitrequest
	wire   [31:0] mm_master_bfm_0_m0_address;                              // mm_master_bfm_0:avm_address -> mm_interconnect_0:mm_master_bfm_0_m0_address
	wire          mm_master_bfm_0_m0_read;                                 // mm_master_bfm_0:avm_read -> mm_interconnect_0:mm_master_bfm_0_m0_read
	wire    [3:0] mm_master_bfm_0_m0_byteenable;                           // mm_master_bfm_0:avm_byteenable -> mm_interconnect_0:mm_master_bfm_0_m0_byteenable
	wire          mm_master_bfm_0_m0_readdatavalid;                        // mm_interconnect_0:mm_master_bfm_0_m0_readdatavalid -> mm_master_bfm_0:avm_readdatavalid
	wire   [31:0] mm_master_bfm_0_m0_writedata;                            // mm_master_bfm_0:avm_writedata -> mm_interconnect_0:mm_master_bfm_0_m0_writedata
	wire          mm_master_bfm_0_m0_write;                                // mm_master_bfm_0:avm_write -> mm_interconnect_0:mm_master_bfm_0_m0_write
	wire    [2:0] mm_master_bfm_0_m0_burstcount;                           // mm_master_bfm_0:avm_burstcount -> mm_interconnect_0:mm_master_bfm_0_m0_burstcount
	wire   [31:0] msgdma_0_mm_read_readdata;                               // mm_interconnect_0:msgdma_0_mm_read_readdata -> msgdma_0:mm_read_readdata
	wire          msgdma_0_mm_read_waitrequest;                            // mm_interconnect_0:msgdma_0_mm_read_waitrequest -> msgdma_0:mm_read_waitrequest
	wire   [11:0] msgdma_0_mm_read_address;                                // msgdma_0:mm_read_address -> mm_interconnect_0:msgdma_0_mm_read_address
	wire          msgdma_0_mm_read_read;                                   // msgdma_0:mm_read_read -> mm_interconnect_0:msgdma_0_mm_read_read
	wire    [3:0] msgdma_0_mm_read_byteenable;                             // msgdma_0:mm_read_byteenable -> mm_interconnect_0:msgdma_0_mm_read_byteenable
	wire          msgdma_0_mm_read_readdatavalid;                          // mm_interconnect_0:msgdma_0_mm_read_readdatavalid -> msgdma_0:mm_read_readdatavalid
	wire   [31:0] mm_interconnect_0_msgdma_0_csr_readdata;                 // msgdma_0:csr_readdata -> mm_interconnect_0:msgdma_0_csr_readdata
	wire    [2:0] mm_interconnect_0_msgdma_0_csr_address;                  // mm_interconnect_0:msgdma_0_csr_address -> msgdma_0:csr_address
	wire          mm_interconnect_0_msgdma_0_csr_read;                     // mm_interconnect_0:msgdma_0_csr_read -> msgdma_0:csr_read
	wire    [3:0] mm_interconnect_0_msgdma_0_csr_byteenable;               // mm_interconnect_0:msgdma_0_csr_byteenable -> msgdma_0:csr_byteenable
	wire          mm_interconnect_0_msgdma_0_csr_write;                    // mm_interconnect_0:msgdma_0_csr_write -> msgdma_0:csr_write
	wire   [31:0] mm_interconnect_0_msgdma_0_csr_writedata;                // mm_interconnect_0:msgdma_0_csr_writedata -> msgdma_0:csr_writedata
	wire          mm_interconnect_0_msgdma_0_descriptor_slave_waitrequest; // msgdma_0:descriptor_slave_waitrequest -> mm_interconnect_0:msgdma_0_descriptor_slave_waitrequest
	wire   [15:0] mm_interconnect_0_msgdma_0_descriptor_slave_byteenable;  // mm_interconnect_0:msgdma_0_descriptor_slave_byteenable -> msgdma_0:descriptor_slave_byteenable
	wire          mm_interconnect_0_msgdma_0_descriptor_slave_write;       // mm_interconnect_0:msgdma_0_descriptor_slave_write -> msgdma_0:descriptor_slave_write
	wire  [127:0] mm_interconnect_0_msgdma_0_descriptor_slave_writedata;   // mm_interconnect_0:msgdma_0_descriptor_slave_writedata -> msgdma_0:descriptor_slave_writedata
	wire          mm_interconnect_0_onchip_memory2_0_s1_chipselect;        // mm_interconnect_0:onchip_memory2_0_s1_chipselect -> onchip_memory2_0:chipselect
	wire   [31:0] mm_interconnect_0_onchip_memory2_0_s1_readdata;          // onchip_memory2_0:readdata -> mm_interconnect_0:onchip_memory2_0_s1_readdata
	wire    [9:0] mm_interconnect_0_onchip_memory2_0_s1_address;           // mm_interconnect_0:onchip_memory2_0_s1_address -> onchip_memory2_0:address
	wire    [3:0] mm_interconnect_0_onchip_memory2_0_s1_byteenable;        // mm_interconnect_0:onchip_memory2_0_s1_byteenable -> onchip_memory2_0:byteenable
	wire          mm_interconnect_0_onchip_memory2_0_s1_write;             // mm_interconnect_0:onchip_memory2_0_s1_write -> onchip_memory2_0:write
	wire   [31:0] mm_interconnect_0_onchip_memory2_0_s1_writedata;         // mm_interconnect_0:onchip_memory2_0_s1_writedata -> onchip_memory2_0:writedata
	wire          mm_interconnect_0_onchip_memory2_0_s1_clken;             // mm_interconnect_0:onchip_memory2_0_s1_clken -> onchip_memory2_0:clken
	wire          msgdma_0_st_source_valid;                                // msgdma_0:st_source_valid -> avalon_st_adapter:in_0_valid
	wire   [31:0] msgdma_0_st_source_data;                                 // msgdma_0:st_source_data -> avalon_st_adapter:in_0_data
	wire          msgdma_0_st_source_ready;                                // avalon_st_adapter:in_0_ready -> msgdma_0:st_source_ready
	wire          avalon_st_adapter_out_0_valid;                           // avalon_st_adapter:out_0_valid -> st_sink_bfm_0:sink_valid
	wire   [31:0] avalon_st_adapter_out_0_data;                            // avalon_st_adapter:out_0_data -> st_sink_bfm_0:sink_data
	wire          avalon_st_adapter_out_0_ready;                           // st_sink_bfm_0:sink_ready -> avalon_st_adapter:out_0_ready
	wire          avalon_st_adapter_out_0_channel;                         // avalon_st_adapter:out_0_channel -> st_sink_bfm_0:sink_channel
	wire          rst_controller_reset_out_reset;                          // rst_controller:reset_out -> [avalon_st_adapter:in_rst_0_reset, mm_interconnect_0:mm_master_bfm_0_clk_reset_reset_bridge_in_reset_reset, mm_master_bfm_0:reset, msgdma_0:reset_n_reset_n, onchip_memory2_0:reset, rst_translator:in_reset, st_sink_bfm_0:reset]
	wire          rst_controller_reset_out_reset_req;                      // rst_controller:reset_req -> [onchip_memory2_0:reset_req, rst_translator:reset_req_in]

	altera_avalon_mm_master_bfm #(
		.AV_ADDRESS_W               (32),
		.AV_SYMBOL_W                (8),
		.AV_NUMSYMBOLS              (4),
		.AV_BURSTCOUNT_W            (3),
		.AV_READRESPONSE_W          (8),
		.AV_WRITERESPONSE_W         (8),
		.USE_READ                   (1),
		.USE_WRITE                  (1),
		.USE_ADDRESS                (1),
		.USE_BYTE_ENABLE            (1),
		.USE_BURSTCOUNT             (1),
		.USE_READ_DATA              (1),
		.USE_READ_DATA_VALID        (1),
		.USE_WRITE_DATA             (1),
		.USE_BEGIN_TRANSFER         (0),
		.USE_BEGIN_BURST_TRANSFER   (0),
		.USE_WAIT_REQUEST           (1),
		.USE_TRANSACTIONID          (0),
		.USE_WRITERESPONSE          (0),
		.USE_READRESPONSE           (0),
		.USE_CLKEN                  (0),
		.AV_CONSTANT_BURST_BEHAVIOR (1),
		.AV_BURST_LINEWRAP          (1),
		.AV_BURST_BNDR_ONLY         (1),
		.AV_MAX_PENDING_READS       (0),
		.AV_MAX_PENDING_WRITES      (0),
		.AV_FIX_READ_LATENCY        (1),
		.AV_READ_WAIT_TIME          (1),
		.AV_WRITE_WAIT_TIME         (0),
		.REGISTER_WAITREQUEST       (0),
		.AV_REGISTERINCOMINGSIGNALS (0),
		.VHDL_ID                    (0)
	) mm_master_bfm_0 (
		.clk                    (clk_clk),                          //       clk.clk
		.reset                  (rst_controller_reset_out_reset),   // clk_reset.reset
		.avm_address            (mm_master_bfm_0_m0_address),       //        m0.address
		.avm_burstcount         (mm_master_bfm_0_m0_burstcount),    //          .burstcount
		.avm_readdata           (mm_master_bfm_0_m0_readdata),      //          .readdata
		.avm_writedata          (mm_master_bfm_0_m0_writedata),     //          .writedata
		.avm_waitrequest        (mm_master_bfm_0_m0_waitrequest),   //          .waitrequest
		.avm_write              (mm_master_bfm_0_m0_write),         //          .write
		.avm_read               (mm_master_bfm_0_m0_read),          //          .read
		.avm_byteenable         (mm_master_bfm_0_m0_byteenable),    //          .byteenable
		.avm_readdatavalid      (mm_master_bfm_0_m0_readdatavalid), //          .readdatavalid
		.avm_begintransfer      (),                                 // (terminated)
		.avm_beginbursttransfer (),                                 // (terminated)
		.avm_arbiterlock        (),                                 // (terminated)
		.avm_lock               (),                                 // (terminated)
		.avm_debugaccess        (),                                 // (terminated)
		.avm_transactionid      (),                                 // (terminated)
		.avm_readid             (8'b00000000),                      // (terminated)
		.avm_writeid            (8'b00000000),                      // (terminated)
		.avm_clken              (),                                 // (terminated)
		.avm_response           (2'b00),                            // (terminated)
		.avm_writeresponsevalid (1'b0),                             // (terminated)
		.avm_readresponse       (8'b00000000),                      // (terminated)
		.avm_writeresponse      (8'b00000000)                       // (terminated)
	);

	AXI_DMA_msgdma_0 msgdma_0 (
		.mm_read_address              (msgdma_0_mm_read_address),                                //          mm_read.address
		.mm_read_read                 (msgdma_0_mm_read_read),                                   //                 .read
		.mm_read_byteenable           (msgdma_0_mm_read_byteenable),                             //                 .byteenable
		.mm_read_readdata             (msgdma_0_mm_read_readdata),                               //                 .readdata
		.mm_read_waitrequest          (msgdma_0_mm_read_waitrequest),                            //                 .waitrequest
		.mm_read_readdatavalid        (msgdma_0_mm_read_readdatavalid),                          //                 .readdatavalid
		.clock_clk                    (clk_clk),                                                 //            clock.clk
		.reset_n_reset_n              (~rst_controller_reset_out_reset),                         //          reset_n.reset_n
		.csr_writedata                (mm_interconnect_0_msgdma_0_csr_writedata),                //              csr.writedata
		.csr_write                    (mm_interconnect_0_msgdma_0_csr_write),                    //                 .write
		.csr_byteenable               (mm_interconnect_0_msgdma_0_csr_byteenable),               //                 .byteenable
		.csr_readdata                 (mm_interconnect_0_msgdma_0_csr_readdata),                 //                 .readdata
		.csr_read                     (mm_interconnect_0_msgdma_0_csr_read),                     //                 .read
		.csr_address                  (mm_interconnect_0_msgdma_0_csr_address),                  //                 .address
		.descriptor_slave_write       (mm_interconnect_0_msgdma_0_descriptor_slave_write),       // descriptor_slave.write
		.descriptor_slave_waitrequest (mm_interconnect_0_msgdma_0_descriptor_slave_waitrequest), //                 .waitrequest
		.descriptor_slave_writedata   (mm_interconnect_0_msgdma_0_descriptor_slave_writedata),   //                 .writedata
		.descriptor_slave_byteenable  (mm_interconnect_0_msgdma_0_descriptor_slave_byteenable),  //                 .byteenable
		.csr_irq_irq                  (msgdma_0_csr_irq_irq),                                    //          csr_irq.irq
		.st_source_data               (msgdma_0_st_source_data),                                 //        st_source.data
		.st_source_valid              (msgdma_0_st_source_valid),                                //                 .valid
		.st_source_ready              (msgdma_0_st_source_ready)                                 //                 .ready
	);

	AXI_DMA_onchip_memory2_0 onchip_memory2_0 (
		.clk        (clk_clk),                                          //   clk1.clk
		.address    (mm_interconnect_0_onchip_memory2_0_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_memory2_0_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_memory2_0_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_memory2_0_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_memory2_0_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_memory2_0_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_memory2_0_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                   // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),               //       .reset_req
		.freeze     (1'b0)                                              // (terminated)
	);

	altera_avalon_st_sink_bfm #(
		.USE_PACKET       (0),
		.USE_CHANNEL      (1),
		.USE_ERROR        (0),
		.USE_READY        (1),
		.USE_VALID        (1),
		.USE_EMPTY        (0),
		.ST_SYMBOL_W      (8),
		.ST_NUMSYMBOLS    (4),
		.ST_CHANNEL_W     (1),
		.ST_ERROR_W       (1),
		.ST_EMPTY_W       (2),
		.ST_READY_LATENCY (0),
		.ST_BEATSPERCYCLE (1),
		.ST_MAX_CHANNELS  (1),
		.VHDL_ID          (0)
	) st_sink_bfm_0 (
		.clk                (clk_clk),                         //       clk.clk
		.reset              (rst_controller_reset_out_reset),  // clk_reset.reset
		.sink_data          (avalon_st_adapter_out_0_data),    //      sink.data
		.sink_valid         (avalon_st_adapter_out_0_valid),   //          .valid
		.sink_ready         (avalon_st_adapter_out_0_ready),   //          .ready
		.sink_channel       (avalon_st_adapter_out_0_channel), //          .channel
		.sink_startofpacket (1'b0),                            // (terminated)
		.sink_endofpacket   (1'b0),                            // (terminated)
		.sink_empty         (2'b00),                           // (terminated)
		.sink_error         (1'b0)                             // (terminated)
	);

	AXI_DMA_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                         (clk_clk),                                                 //                                       clk_0_clk.clk
		.mm_master_bfm_0_clk_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                          // mm_master_bfm_0_clk_reset_reset_bridge_in_reset.reset
		.mm_master_bfm_0_m0_address                            (mm_master_bfm_0_m0_address),                              //                              mm_master_bfm_0_m0.address
		.mm_master_bfm_0_m0_waitrequest                        (mm_master_bfm_0_m0_waitrequest),                          //                                                .waitrequest
		.mm_master_bfm_0_m0_burstcount                         (mm_master_bfm_0_m0_burstcount),                           //                                                .burstcount
		.mm_master_bfm_0_m0_byteenable                         (mm_master_bfm_0_m0_byteenable),                           //                                                .byteenable
		.mm_master_bfm_0_m0_read                               (mm_master_bfm_0_m0_read),                                 //                                                .read
		.mm_master_bfm_0_m0_readdata                           (mm_master_bfm_0_m0_readdata),                             //                                                .readdata
		.mm_master_bfm_0_m0_readdatavalid                      (mm_master_bfm_0_m0_readdatavalid),                        //                                                .readdatavalid
		.mm_master_bfm_0_m0_write                              (mm_master_bfm_0_m0_write),                                //                                                .write
		.mm_master_bfm_0_m0_writedata                          (mm_master_bfm_0_m0_writedata),                            //                                                .writedata
		.msgdma_0_mm_read_address                              (msgdma_0_mm_read_address),                                //                                msgdma_0_mm_read.address
		.msgdma_0_mm_read_waitrequest                          (msgdma_0_mm_read_waitrequest),                            //                                                .waitrequest
		.msgdma_0_mm_read_byteenable                           (msgdma_0_mm_read_byteenable),                             //                                                .byteenable
		.msgdma_0_mm_read_read                                 (msgdma_0_mm_read_read),                                   //                                                .read
		.msgdma_0_mm_read_readdata                             (msgdma_0_mm_read_readdata),                               //                                                .readdata
		.msgdma_0_mm_read_readdatavalid                        (msgdma_0_mm_read_readdatavalid),                          //                                                .readdatavalid
		.msgdma_0_csr_address                                  (mm_interconnect_0_msgdma_0_csr_address),                  //                                    msgdma_0_csr.address
		.msgdma_0_csr_write                                    (mm_interconnect_0_msgdma_0_csr_write),                    //                                                .write
		.msgdma_0_csr_read                                     (mm_interconnect_0_msgdma_0_csr_read),                     //                                                .read
		.msgdma_0_csr_readdata                                 (mm_interconnect_0_msgdma_0_csr_readdata),                 //                                                .readdata
		.msgdma_0_csr_writedata                                (mm_interconnect_0_msgdma_0_csr_writedata),                //                                                .writedata
		.msgdma_0_csr_byteenable                               (mm_interconnect_0_msgdma_0_csr_byteenable),               //                                                .byteenable
		.msgdma_0_descriptor_slave_write                       (mm_interconnect_0_msgdma_0_descriptor_slave_write),       //                       msgdma_0_descriptor_slave.write
		.msgdma_0_descriptor_slave_writedata                   (mm_interconnect_0_msgdma_0_descriptor_slave_writedata),   //                                                .writedata
		.msgdma_0_descriptor_slave_byteenable                  (mm_interconnect_0_msgdma_0_descriptor_slave_byteenable),  //                                                .byteenable
		.msgdma_0_descriptor_slave_waitrequest                 (mm_interconnect_0_msgdma_0_descriptor_slave_waitrequest), //                                                .waitrequest
		.onchip_memory2_0_s1_address                           (mm_interconnect_0_onchip_memory2_0_s1_address),           //                             onchip_memory2_0_s1.address
		.onchip_memory2_0_s1_write                             (mm_interconnect_0_onchip_memory2_0_s1_write),             //                                                .write
		.onchip_memory2_0_s1_readdata                          (mm_interconnect_0_onchip_memory2_0_s1_readdata),          //                                                .readdata
		.onchip_memory2_0_s1_writedata                         (mm_interconnect_0_onchip_memory2_0_s1_writedata),         //                                                .writedata
		.onchip_memory2_0_s1_byteenable                        (mm_interconnect_0_onchip_memory2_0_s1_byteenable),        //                                                .byteenable
		.onchip_memory2_0_s1_chipselect                        (mm_interconnect_0_onchip_memory2_0_s1_chipselect),        //                                                .chipselect
		.onchip_memory2_0_s1_clken                             (mm_interconnect_0_onchip_memory2_0_s1_clken)              //                                                .clken
	);

	AXI_DMA_avalon_st_adapter #(
		.inBitsPerSymbol (8),
		.inUsePackets    (0),
		.inDataWidth     (32),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (32),
		.outChannelWidth (1),
		.outErrorWidth   (0),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clk_clk),                         // in_clk_0.clk
		.in_rst_0_reset (rst_controller_reset_out_reset),  // in_rst_0.reset
		.in_0_data      (msgdma_0_st_source_data),         //     in_0.data
		.in_0_valid     (msgdma_0_st_source_valid),        //         .valid
		.in_0_ready     (msgdma_0_st_source_ready),        //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),    //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),   //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),   //         .ready
		.out_0_channel  (avalon_st_adapter_out_0_channel)  //         .channel
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
