// AXI_DMA.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module AXI_DMA (
		input  wire  clk_clk,              //              clk.clk
		output wire  msgdma_0_csr_irq_irq, // msgdma_0_csr_irq.irq
		input  wire  reset_reset_n         //            reset.reset_n
	);

	wire   [31:0] mgc_axi4lite_master_0_altera_axi4lite_master_awaddr;                  // mgc_axi4lite_master_0:AWADDR -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_awaddr
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_arready;                 // mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_arready -> mgc_axi4lite_master_0:ARREADY
	wire    [1:0] mgc_axi4lite_master_0_altera_axi4lite_master_bresp;                   // mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_bresp -> mgc_axi4lite_master_0:BRESP
	wire   [31:0] mgc_axi4lite_master_0_altera_axi4lite_master_rdata;                   // mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_rdata -> mgc_axi4lite_master_0:RDATA
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_wready;                  // mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_wready -> mgc_axi4lite_master_0:WREADY
	wire    [3:0] mgc_axi4lite_master_0_altera_axi4lite_master_wstrb;                   // mgc_axi4lite_master_0:WSTRB -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_wstrb
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_awready;                 // mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_awready -> mgc_axi4lite_master_0:AWREADY
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_rready;                  // mgc_axi4lite_master_0:RREADY -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_rready
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_bready;                  // mgc_axi4lite_master_0:BREADY -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_bready
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_wvalid;                  // mgc_axi4lite_master_0:WVALID -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_wvalid
	wire   [31:0] mgc_axi4lite_master_0_altera_axi4lite_master_araddr;                  // mgc_axi4lite_master_0:ARADDR -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_araddr
	wire    [2:0] mgc_axi4lite_master_0_altera_axi4lite_master_arprot;                  // mgc_axi4lite_master_0:ARPROT -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_arprot
	wire    [1:0] mgc_axi4lite_master_0_altera_axi4lite_master_rresp;                   // mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_rresp -> mgc_axi4lite_master_0:RRESP
	wire    [2:0] mgc_axi4lite_master_0_altera_axi4lite_master_awprot;                  // mgc_axi4lite_master_0:AWPROT -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_awprot
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_arvalid;                 // mgc_axi4lite_master_0:ARVALID -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_arvalid
	wire   [31:0] mgc_axi4lite_master_0_altera_axi4lite_master_wdata;                   // mgc_axi4lite_master_0:WDATA -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_wdata
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_bvalid;                  // mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_bvalid -> mgc_axi4lite_master_0:BVALID
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_awvalid;                 // mgc_axi4lite_master_0:AWVALID -> mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_awvalid
	wire          mgc_axi4lite_master_0_altera_axi4lite_master_rvalid;                  // mm_interconnect_0:mgc_axi4lite_master_0_altera_axi4lite_master_rvalid -> mgc_axi4lite_master_0:RVALID
	wire   [31:0] mm_interconnect_0_msgdma_0_csr_readdata;                              // msgdma_0:csr_readdata -> mm_interconnect_0:msgdma_0_csr_readdata
	wire    [2:0] mm_interconnect_0_msgdma_0_csr_address;                               // mm_interconnect_0:msgdma_0_csr_address -> msgdma_0:csr_address
	wire          mm_interconnect_0_msgdma_0_csr_read;                                  // mm_interconnect_0:msgdma_0_csr_read -> msgdma_0:csr_read
	wire    [3:0] mm_interconnect_0_msgdma_0_csr_byteenable;                            // mm_interconnect_0:msgdma_0_csr_byteenable -> msgdma_0:csr_byteenable
	wire          mm_interconnect_0_msgdma_0_csr_write;                                 // mm_interconnect_0:msgdma_0_csr_write -> msgdma_0:csr_write
	wire   [31:0] mm_interconnect_0_msgdma_0_csr_writedata;                             // mm_interconnect_0:msgdma_0_csr_writedata -> msgdma_0:csr_writedata
	wire          mm_interconnect_0_msgdma_0_descriptor_slave_waitrequest;              // msgdma_0:descriptor_slave_waitrequest -> mm_interconnect_0:msgdma_0_descriptor_slave_waitrequest
	wire   [15:0] mm_interconnect_0_msgdma_0_descriptor_slave_byteenable;               // mm_interconnect_0:msgdma_0_descriptor_slave_byteenable -> msgdma_0:descriptor_slave_byteenable
	wire          mm_interconnect_0_msgdma_0_descriptor_slave_write;                    // mm_interconnect_0:msgdma_0_descriptor_slave_write -> msgdma_0:descriptor_slave_write
	wire  [127:0] mm_interconnect_0_msgdma_0_descriptor_slave_writedata;                // mm_interconnect_0:msgdma_0_descriptor_slave_writedata -> msgdma_0:descriptor_slave_writedata
	wire   [31:0] msgdma_0_mm_read_readdata;                                            // mm_interconnect_1:msgdma_0_mm_read_readdata -> msgdma_0:mm_read_readdata
	wire          msgdma_0_mm_read_waitrequest;                                         // mm_interconnect_1:msgdma_0_mm_read_waitrequest -> msgdma_0:mm_read_waitrequest
	wire   [31:0] msgdma_0_mm_read_address;                                             // msgdma_0:mm_read_address -> mm_interconnect_1:msgdma_0_mm_read_address
	wire          msgdma_0_mm_read_read;                                                // msgdma_0:mm_read_read -> mm_interconnect_1:msgdma_0_mm_read_read
	wire    [3:0] msgdma_0_mm_read_byteenable;                                          // msgdma_0:mm_read_byteenable -> mm_interconnect_1:msgdma_0_mm_read_byteenable
	wire          msgdma_0_mm_read_readdatavalid;                                       // mm_interconnect_1:msgdma_0_mm_read_readdatavalid -> msgdma_0:mm_read_readdatavalid
	wire   [31:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awaddr;  // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_awaddr -> mgc_axi4lite_slave_0:AWADDR
	wire    [1:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bresp;   // mgc_axi4lite_slave_0:BRESP -> mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_bresp
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arready; // mgc_axi4lite_slave_0:ARREADY -> mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_arready
	wire   [31:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rdata;   // mgc_axi4lite_slave_0:RDATA -> mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_rdata
	wire    [3:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wstrb;   // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_wstrb -> mgc_axi4lite_slave_0:WSTRB
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wready;  // mgc_axi4lite_slave_0:WREADY -> mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_wready
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awready; // mgc_axi4lite_slave_0:AWREADY -> mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_awready
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rready;  // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_rready -> mgc_axi4lite_slave_0:RREADY
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bready;  // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_bready -> mgc_axi4lite_slave_0:BREADY
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wvalid;  // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_wvalid -> mgc_axi4lite_slave_0:WVALID
	wire   [31:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_araddr;  // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_araddr -> mgc_axi4lite_slave_0:ARADDR
	wire    [2:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arprot;  // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_arprot -> mgc_axi4lite_slave_0:ARPROT
	wire    [1:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rresp;   // mgc_axi4lite_slave_0:RRESP -> mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_rresp
	wire    [2:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awprot;  // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_awprot -> mgc_axi4lite_slave_0:AWPROT
	wire   [31:0] mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wdata;   // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_wdata -> mgc_axi4lite_slave_0:WDATA
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arvalid; // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_arvalid -> mgc_axi4lite_slave_0:ARVALID
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bvalid;  // mgc_axi4lite_slave_0:BVALID -> mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_bvalid
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awvalid; // mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_awvalid -> mgc_axi4lite_slave_0:AWVALID
	wire          mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rvalid;  // mgc_axi4lite_slave_0:RVALID -> mm_interconnect_1:mgc_axi4lite_slave_0_altera_axi4lite_slave_rvalid
	wire          msgdma_0_st_source_valid;                                             // msgdma_0:st_source_valid -> avalon_st_adapter:in_0_valid
	wire   [31:0] msgdma_0_st_source_data;                                              // msgdma_0:st_source_data -> avalon_st_adapter:in_0_data
	wire          msgdma_0_st_source_ready;                                             // avalon_st_adapter:in_0_ready -> msgdma_0:st_source_ready
	wire          avalon_st_adapter_out_0_valid;                                        // avalon_st_adapter:out_0_valid -> st_sink_bfm_0:sink_valid
	wire   [31:0] avalon_st_adapter_out_0_data;                                         // avalon_st_adapter:out_0_data -> st_sink_bfm_0:sink_data
	wire          avalon_st_adapter_out_0_ready;                                        // st_sink_bfm_0:sink_ready -> avalon_st_adapter:out_0_ready
	wire          avalon_st_adapter_out_0_channel;                                      // avalon_st_adapter:out_0_channel -> st_sink_bfm_0:sink_channel
	wire          rst_controller_reset_out_reset;                                       // rst_controller:reset_out -> [avalon_st_adapter:in_rst_0_reset, mgc_axi4lite_master_0:ARESETn, mgc_axi4lite_slave_0:ARESETn, mm_interconnect_0:mgc_axi4lite_master_0_reset_sink_reset_bridge_in_reset_reset, mm_interconnect_1:msgdma_0_reset_n_reset_bridge_in_reset_reset, msgdma_0:reset_n_reset_n, st_sink_bfm_0:reset]

	AXI_DMA_mgc_axi4lite_master_0 mgc_axi4lite_master_0 (
		.AWVALID (mgc_axi4lite_master_0_altera_axi4lite_master_awvalid), // altera_axi4lite_master.awvalid
		.AWPROT  (mgc_axi4lite_master_0_altera_axi4lite_master_awprot),  //                       .awprot
		.AWREADY (mgc_axi4lite_master_0_altera_axi4lite_master_awready), //                       .awready
		.ARVALID (mgc_axi4lite_master_0_altera_axi4lite_master_arvalid), //                       .arvalid
		.ARPROT  (mgc_axi4lite_master_0_altera_axi4lite_master_arprot),  //                       .arprot
		.ARREADY (mgc_axi4lite_master_0_altera_axi4lite_master_arready), //                       .arready
		.RVALID  (mgc_axi4lite_master_0_altera_axi4lite_master_rvalid),  //                       .rvalid
		.RRESP   (mgc_axi4lite_master_0_altera_axi4lite_master_rresp),   //                       .rresp
		.RREADY  (mgc_axi4lite_master_0_altera_axi4lite_master_rready),  //                       .rready
		.WVALID  (mgc_axi4lite_master_0_altera_axi4lite_master_wvalid),  //                       .wvalid
		.WREADY  (mgc_axi4lite_master_0_altera_axi4lite_master_wready),  //                       .wready
		.BVALID  (mgc_axi4lite_master_0_altera_axi4lite_master_bvalid),  //                       .bvalid
		.BRESP   (mgc_axi4lite_master_0_altera_axi4lite_master_bresp),   //                       .bresp
		.BREADY  (mgc_axi4lite_master_0_altera_axi4lite_master_bready),  //                       .bready
		.AWADDR  (mgc_axi4lite_master_0_altera_axi4lite_master_awaddr),  //                       .awaddr
		.ARADDR  (mgc_axi4lite_master_0_altera_axi4lite_master_araddr),  //                       .araddr
		.RDATA   (mgc_axi4lite_master_0_altera_axi4lite_master_rdata),   //                       .rdata
		.WDATA   (mgc_axi4lite_master_0_altera_axi4lite_master_wdata),   //                       .wdata
		.WSTRB   (mgc_axi4lite_master_0_altera_axi4lite_master_wstrb),   //                       .wstrb
		.ACLK    (clk_clk),                                              //             clock_sink.clk
		.ARESETn (~rst_controller_reset_out_reset)                       //             reset_sink.reset_n
	);

	AXI_DMA_mgc_axi4lite_slave_0 mgc_axi4lite_slave_0 (
		.AWVALID (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awvalid), // altera_axi4lite_slave.awvalid
		.AWPROT  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awprot),  //                      .awprot
		.AWREADY (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awready), //                      .awready
		.ARVALID (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arvalid), //                      .arvalid
		.ARPROT  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arprot),  //                      .arprot
		.ARREADY (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arready), //                      .arready
		.RVALID  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rvalid),  //                      .rvalid
		.RRESP   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rresp),   //                      .rresp
		.RREADY  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rready),  //                      .rready
		.WVALID  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wvalid),  //                      .wvalid
		.WREADY  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wready),  //                      .wready
		.BVALID  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bvalid),  //                      .bvalid
		.BRESP   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bresp),   //                      .bresp
		.BREADY  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bready),  //                      .bready
		.AWADDR  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awaddr),  //                      .awaddr
		.ARADDR  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_araddr),  //                      .araddr
		.RDATA   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rdata),   //                      .rdata
		.WDATA   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wdata),   //                      .wdata
		.WSTRB   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wstrb),   //                      .wstrb
		.ACLK    (clk_clk),                                                              //            clock_sink.clk
		.ARESETn (~rst_controller_reset_out_reset)                                       //            reset_sink.reset_n
	);

	AXI_DMA_msgdma_0 msgdma_0 (
		.mm_read_address              (msgdma_0_mm_read_address),                                //          mm_read.address
		.mm_read_read                 (msgdma_0_mm_read_read),                                   //                 .read
		.mm_read_byteenable           (msgdma_0_mm_read_byteenable),                             //                 .byteenable
		.mm_read_readdata             (msgdma_0_mm_read_readdata),                               //                 .readdata
		.mm_read_waitrequest          (msgdma_0_mm_read_waitrequest),                            //                 .waitrequest
		.mm_read_readdatavalid        (msgdma_0_mm_read_readdatavalid),                          //                 .readdatavalid
		.clock_clk                    (clk_clk),                                                 //            clock.clk
		.reset_n_reset_n              (~rst_controller_reset_out_reset),                         //          reset_n.reset_n
		.csr_writedata                (mm_interconnect_0_msgdma_0_csr_writedata),                //              csr.writedata
		.csr_write                    (mm_interconnect_0_msgdma_0_csr_write),                    //                 .write
		.csr_byteenable               (mm_interconnect_0_msgdma_0_csr_byteenable),               //                 .byteenable
		.csr_readdata                 (mm_interconnect_0_msgdma_0_csr_readdata),                 //                 .readdata
		.csr_read                     (mm_interconnect_0_msgdma_0_csr_read),                     //                 .read
		.csr_address                  (mm_interconnect_0_msgdma_0_csr_address),                  //                 .address
		.descriptor_slave_write       (mm_interconnect_0_msgdma_0_descriptor_slave_write),       // descriptor_slave.write
		.descriptor_slave_waitrequest (mm_interconnect_0_msgdma_0_descriptor_slave_waitrequest), //                 .waitrequest
		.descriptor_slave_writedata   (mm_interconnect_0_msgdma_0_descriptor_slave_writedata),   //                 .writedata
		.descriptor_slave_byteenable  (mm_interconnect_0_msgdma_0_descriptor_slave_byteenable),  //                 .byteenable
		.csr_irq_irq                  (msgdma_0_csr_irq_irq),                                    //          csr_irq.irq
		.st_source_data               (msgdma_0_st_source_data),                                 //        st_source.data
		.st_source_valid              (msgdma_0_st_source_valid),                                //                 .valid
		.st_source_ready              (msgdma_0_st_source_ready)                                 //                 .ready
	);

	altera_avalon_st_sink_bfm #(
		.USE_PACKET       (0),
		.USE_CHANNEL      (1),
		.USE_ERROR        (0),
		.USE_READY        (1),
		.USE_VALID        (1),
		.USE_EMPTY        (0),
		.ST_SYMBOL_W      (8),
		.ST_NUMSYMBOLS    (4),
		.ST_CHANNEL_W     (1),
		.ST_ERROR_W       (1),
		.ST_EMPTY_W       (2),
		.ST_READY_LATENCY (0),
		.ST_BEATSPERCYCLE (1),
		.ST_MAX_CHANNELS  (1),
		.VHDL_ID          (0)
	) st_sink_bfm_0 (
		.clk                (clk_clk),                         //       clk.clk
		.reset              (rst_controller_reset_out_reset),  // clk_reset.reset
		.sink_data          (avalon_st_adapter_out_0_data),    //      sink.data
		.sink_valid         (avalon_st_adapter_out_0_valid),   //          .valid
		.sink_ready         (avalon_st_adapter_out_0_ready),   //          .ready
		.sink_channel       (avalon_st_adapter_out_0_channel), //          .channel
		.sink_startofpacket (1'b0),                            // (terminated)
		.sink_endofpacket   (1'b0),                            // (terminated)
		.sink_empty         (2'b00),                           // (terminated)
		.sink_error         (1'b0)                             // (terminated)
	);

	AXI_DMA_mm_interconnect_0 mm_interconnect_0 (
		.mgc_axi4lite_master_0_altera_axi4lite_master_awaddr          (mgc_axi4lite_master_0_altera_axi4lite_master_awaddr),     //           mgc_axi4lite_master_0_altera_axi4lite_master.awaddr
		.mgc_axi4lite_master_0_altera_axi4lite_master_awprot          (mgc_axi4lite_master_0_altera_axi4lite_master_awprot),     //                                                       .awprot
		.mgc_axi4lite_master_0_altera_axi4lite_master_awvalid         (mgc_axi4lite_master_0_altera_axi4lite_master_awvalid),    //                                                       .awvalid
		.mgc_axi4lite_master_0_altera_axi4lite_master_awready         (mgc_axi4lite_master_0_altera_axi4lite_master_awready),    //                                                       .awready
		.mgc_axi4lite_master_0_altera_axi4lite_master_wdata           (mgc_axi4lite_master_0_altera_axi4lite_master_wdata),      //                                                       .wdata
		.mgc_axi4lite_master_0_altera_axi4lite_master_wstrb           (mgc_axi4lite_master_0_altera_axi4lite_master_wstrb),      //                                                       .wstrb
		.mgc_axi4lite_master_0_altera_axi4lite_master_wvalid          (mgc_axi4lite_master_0_altera_axi4lite_master_wvalid),     //                                                       .wvalid
		.mgc_axi4lite_master_0_altera_axi4lite_master_wready          (mgc_axi4lite_master_0_altera_axi4lite_master_wready),     //                                                       .wready
		.mgc_axi4lite_master_0_altera_axi4lite_master_bresp           (mgc_axi4lite_master_0_altera_axi4lite_master_bresp),      //                                                       .bresp
		.mgc_axi4lite_master_0_altera_axi4lite_master_bvalid          (mgc_axi4lite_master_0_altera_axi4lite_master_bvalid),     //                                                       .bvalid
		.mgc_axi4lite_master_0_altera_axi4lite_master_bready          (mgc_axi4lite_master_0_altera_axi4lite_master_bready),     //                                                       .bready
		.mgc_axi4lite_master_0_altera_axi4lite_master_araddr          (mgc_axi4lite_master_0_altera_axi4lite_master_araddr),     //                                                       .araddr
		.mgc_axi4lite_master_0_altera_axi4lite_master_arprot          (mgc_axi4lite_master_0_altera_axi4lite_master_arprot),     //                                                       .arprot
		.mgc_axi4lite_master_0_altera_axi4lite_master_arvalid         (mgc_axi4lite_master_0_altera_axi4lite_master_arvalid),    //                                                       .arvalid
		.mgc_axi4lite_master_0_altera_axi4lite_master_arready         (mgc_axi4lite_master_0_altera_axi4lite_master_arready),    //                                                       .arready
		.mgc_axi4lite_master_0_altera_axi4lite_master_rdata           (mgc_axi4lite_master_0_altera_axi4lite_master_rdata),      //                                                       .rdata
		.mgc_axi4lite_master_0_altera_axi4lite_master_rresp           (mgc_axi4lite_master_0_altera_axi4lite_master_rresp),      //                                                       .rresp
		.mgc_axi4lite_master_0_altera_axi4lite_master_rvalid          (mgc_axi4lite_master_0_altera_axi4lite_master_rvalid),     //                                                       .rvalid
		.mgc_axi4lite_master_0_altera_axi4lite_master_rready          (mgc_axi4lite_master_0_altera_axi4lite_master_rready),     //                                                       .rready
		.clk_0_clk_clk                                                (clk_clk),                                                 //                                              clk_0_clk.clk
		.mgc_axi4lite_master_0_reset_sink_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                          // mgc_axi4lite_master_0_reset_sink_reset_bridge_in_reset.reset
		.msgdma_0_csr_address                                         (mm_interconnect_0_msgdma_0_csr_address),                  //                                           msgdma_0_csr.address
		.msgdma_0_csr_write                                           (mm_interconnect_0_msgdma_0_csr_write),                    //                                                       .write
		.msgdma_0_csr_read                                            (mm_interconnect_0_msgdma_0_csr_read),                     //                                                       .read
		.msgdma_0_csr_readdata                                        (mm_interconnect_0_msgdma_0_csr_readdata),                 //                                                       .readdata
		.msgdma_0_csr_writedata                                       (mm_interconnect_0_msgdma_0_csr_writedata),                //                                                       .writedata
		.msgdma_0_csr_byteenable                                      (mm_interconnect_0_msgdma_0_csr_byteenable),               //                                                       .byteenable
		.msgdma_0_descriptor_slave_write                              (mm_interconnect_0_msgdma_0_descriptor_slave_write),       //                              msgdma_0_descriptor_slave.write
		.msgdma_0_descriptor_slave_writedata                          (mm_interconnect_0_msgdma_0_descriptor_slave_writedata),   //                                                       .writedata
		.msgdma_0_descriptor_slave_byteenable                         (mm_interconnect_0_msgdma_0_descriptor_slave_byteenable),  //                                                       .byteenable
		.msgdma_0_descriptor_slave_waitrequest                        (mm_interconnect_0_msgdma_0_descriptor_slave_waitrequest)  //                                                       .waitrequest
	);

	AXI_DMA_mm_interconnect_1 mm_interconnect_1 (
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_awaddr  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awaddr),  // mgc_axi4lite_slave_0_altera_axi4lite_slave.awaddr
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_awprot  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awprot),  //                                           .awprot
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_awvalid (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awvalid), //                                           .awvalid
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_awready (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_awready), //                                           .awready
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_wdata   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wdata),   //                                           .wdata
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_wstrb   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wstrb),   //                                           .wstrb
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_wvalid  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wvalid),  //                                           .wvalid
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_wready  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_wready),  //                                           .wready
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_bresp   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bresp),   //                                           .bresp
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_bvalid  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bvalid),  //                                           .bvalid
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_bready  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_bready),  //                                           .bready
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_araddr  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_araddr),  //                                           .araddr
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_arprot  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arprot),  //                                           .arprot
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_arvalid (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arvalid), //                                           .arvalid
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_arready (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_arready), //                                           .arready
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_rdata   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rdata),   //                                           .rdata
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_rresp   (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rresp),   //                                           .rresp
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_rvalid  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rvalid),  //                                           .rvalid
		.mgc_axi4lite_slave_0_altera_axi4lite_slave_rready  (mm_interconnect_1_mgc_axi4lite_slave_0_altera_axi4lite_slave_rready),  //                                           .rready
		.clk_0_clk_clk                                      (clk_clk),                                                              //                                  clk_0_clk.clk
		.msgdma_0_reset_n_reset_bridge_in_reset_reset       (rst_controller_reset_out_reset),                                       //     msgdma_0_reset_n_reset_bridge_in_reset.reset
		.msgdma_0_mm_read_address                           (msgdma_0_mm_read_address),                                             //                           msgdma_0_mm_read.address
		.msgdma_0_mm_read_waitrequest                       (msgdma_0_mm_read_waitrequest),                                         //                                           .waitrequest
		.msgdma_0_mm_read_byteenable                        (msgdma_0_mm_read_byteenable),                                          //                                           .byteenable
		.msgdma_0_mm_read_read                              (msgdma_0_mm_read_read),                                                //                                           .read
		.msgdma_0_mm_read_readdata                          (msgdma_0_mm_read_readdata),                                            //                                           .readdata
		.msgdma_0_mm_read_readdatavalid                     (msgdma_0_mm_read_readdatavalid)                                        //                                           .readdatavalid
	);

	AXI_DMA_avalon_st_adapter #(
		.inBitsPerSymbol (8),
		.inUsePackets    (0),
		.inDataWidth     (32),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (32),
		.outChannelWidth (1),
		.outErrorWidth   (0),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clk_clk),                         // in_clk_0.clk
		.in_rst_0_reset (rst_controller_reset_out_reset),  // in_rst_0.reset
		.in_0_data      (msgdma_0_st_source_data),         //     in_0.data
		.in_0_valid     (msgdma_0_st_source_valid),        //         .valid
		.in_0_ready     (msgdma_0_st_source_ready),        //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),    //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),   //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),   //         .ready
		.out_0_channel  (avalon_st_adapter_out_0_channel)  //         .channel
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
